from django.core.management.base import BaseCommand

from daily_random_events.models import Activity


LEGACY_TITLES = [
    "Visit a nearby bookstore",
    "Try a new cafe and journal",
    "Walk a new neighborhood route",
    "Call one friend for a catch-up",
    "Cook one simple new recipe",
    "Do a 20-minute bodyweight workout",
    "Visit a local museum or gallery",
    "Picnic in a nearby park",
    "Host a board game night",
    "Declutter one drawer or shelf",
    "Watch a documentary on a new topic",
    "Join a drop-in class",
    "Build a comfort playlist",
    "Take yourself out for dessert",
    "Sunset photo walk",
    "Try a new stretching routine",
    "Browse a secondhand shop",
    "Swap recommendations with a friend",
    "Visit a weekend market",
    "Cook breakfast for dinner",
    "Take a short cycling route",
    "Try a guided meditation session",
    "Explore a campus talk",
    "Practice a quick dance class online",
    "Meet a friend for a walk-and-talk",
    "Play a pickup sport",
    "Try one new sketching prompt",
    "Plan a mini room refresh",
    "Do a 15-minute partner workout burst",
    "Have a rapid-fire snack crawl",
    "Run a 15-minute challenge round",
    "Make a tea-and-reset break",
    "Take a solo idea walk",
    "Do a speed clean sprint",
    "Share a cozy voice note exchange",
    "Meet for a quick coffee catch-up",
    "Challenge a friend to a step race",
    "Read in a quiet corner",
    "Try one new neighborhood cafe",
    "Take a brisk power walk",
    "Plan a themed dinner with a friend",
    "Spend an afternoon at a game cafe",
    "Take a long photo walk together",
    "Attend a pop-up workshop with a friend",
    "Do a museum and snack visit together",
    "Book a doubles court or practice slot",
    "Take a focused gym session",
    "Spend a long block on a creative sprint",
    "Do a solo day-trip photo route",
    "Settle into a deep reading cafe session",
    "Take a self-guided gallery route",
    "Join a premium online masterclass",
    "Book a half-day studio session",
    "Plan a brunch and browse outing",
    "Take a scenic train or bus loop",
]


def build_activity(
    title,
    description,
    *,
    category,
    min_time,
    max_time,
    min_budget,
    max_budget,
    moods,
    social_type,
    is_outdoor=False,
):
    return {
        "title": title,
        "description": description,
        "category": category,
        "min_time_minutes": min_time,
        "max_time_minutes": max_time,
        "min_budget": f"{int(min_budget)}.00",
        "max_budget": f"{int(max_budget)}.00",
        "mood_tags": list(moods),
        "social_type": social_type,
        "is_outdoor": is_outdoor,
        "is_active": True,
    }


SEED_ACTIVITIES = [
    build_activity(
        "Tea and reset",
        "Brew something warm and give yourself a quiet pause.",
        category="HOME",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=5,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Cozy reading break",
        "Find a calm corner and read a few pages.",
        category="INDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Comfort playlist",
        "Build a short playlist that fits your mood today.",
        category="INDOOR",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Idea walk",
        "Take a slow walk and think through one small thing.",
        category="OUTDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
        is_outdoor=True,
    ),
    build_activity(
        "Sunset photo stroll",
        "Capture five little details as the light changes.",
        category="OUTDOOR",
        min_time=20,
        max_time=45,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Window light reset",
        "Open a window and shift the light for a soft refresh.",
        category="HOME",
        min_time=10,
        max_time=15,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Slow sketch moment",
        "Fill one page without worrying about the result.",
        category="CLASS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=5,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Plant care pause",
        "Water or trim one plant and notice the change.",
        category="HOME",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=5,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Documentary detour",
        "Watch something outside your usual picks.",
        category="INDOOR",
        min_time=30,
        max_time=90,
        min_budget=0,
        max_budget=15,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Desk reset ritual",
        "Clear one surface and set it up nicely.",
        category="HOME",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Voice note exchange",
        "Send one thoughtful message and listen back slowly.",
        category="SOCIAL",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Solo dessert pause",
        "Enjoy something sweet without multitasking.",
        category="FOOD",
        min_time=20,
        max_time=45,
        min_budget=5,
        max_budget=15,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Library wander",
        "Browse one shelf you normally skip.",
        category="INDOOR",
        min_time=20,
        max_time=60,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Quiet journal page",
        "Write one honest page without editing it.",
        category="INDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Album revisit",
        "Listen through one full album from start to finish.",
        category="INDOOR",
        min_time=35,
        max_time=60,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Photo color hunt",
        "Take five photos around one simple theme.",
        category="OUTDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Slow stretch reset",
        "Loosen your shoulders, hips, and back gently.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Calm corner cleanup",
        "Tidy one small area at an easy pace.",
        category="HOME",
        min_time=15,
        max_time=25,
        min_budget=0,
        max_budget=0,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Rainy day tea break",
        "Lean into a cozy, low-pressure moment.",
        category="HOME",
        min_time=10,
        max_time=20,
        min_budget=0,
        max_budget=5,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Soft morning start",
        "Wake up gently and avoid rushing into the day.",
        category="HOME",
        min_time=20,
        max_time=40,
        min_budget=0,
        max_budget=5,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "New cafe moment",
        "Try a nearby spot and enjoy a small change of scene.",
        category="FOOD",
        min_time=20,
        max_time=45,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Bookstore wander",
        "Browse and leave with one good find.",
        category="INDOOR",
        min_time=30,
        max_time=90,
        min_budget=0,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Neighborhood explore",
        "Walk a new route and notice three small details.",
        category="OUTDOOR",
        min_time=20,
        max_time=60,
        min_budget=0,
        max_budget=0,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Simple recipe night",
        "Make one easy dish you have not tried before.",
        category="HOME",
        min_time=30,
        max_time=75,
        min_budget=8,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Weekend market wander",
        "Explore one section you would usually skip.",
        category="OUTDOOR",
        min_time=45,
        max_time=90,
        min_budget=0,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Drop-in class",
        "Try a one-off yoga, dance, or art session.",
        category="CLASS",
        min_time=60,
        max_time=120,
        min_budget=10,
        max_budget=30,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Mini room refresh",
        "Rearrange one corner for a small reset.",
        category="HOME",
        min_time=25,
        max_time=60,
        min_budget=0,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Sketch prompt session",
        "Fill one page around a single theme.",
        category="CLASS",
        min_time=20,
        max_time=45,
        min_budget=0,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Conversation swap",
        "Trade one recommendation with a friend.",
        category="SOCIAL",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["medium"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Park picnic pause",
        "Bring a simple snack and sit outside for a while.",
        category="OUTDOOR",
        min_time=45,
        max_time=90,
        min_budget=0,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Secondhand surprise",
        "Visit a thrift shop and look for something unexpected.",
        category="INDOOR",
        min_time=25,
        max_time=60,
        min_budget=0,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Bus ride mini-adventure",
        "Ride to the end of a short route just to see.",
        category="OUTDOOR",
        min_time=30,
        max_time=75,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Breakfast for dinner",
        "Lean into the novelty and keep it simple.",
        category="HOME",
        min_time=30,
        max_time=60,
        min_budget=8,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Cafe journal hour",
        "Order one drink and write a few thoughts.",
        category="FOOD",
        min_time=30,
        max_time=60,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Gallery pause",
        "Spend time with one exhibit you would normally pass.",
        category="CULTURE",
        min_time=60,
        max_time=120,
        min_budget=10,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Walk-and-talk catch-up",
        "Let the walk be the plan.",
        category="SOCIAL",
        min_time=20,
        max_time=60,
        min_budget=0,
        max_budget=0,
        moods=["medium"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Market sample stop",
        "Try one thing and move on.",
        category="OUTDOOR",
        min_time=20,
        max_time=45,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Photo theme walk",
        "Collect a set of photos around one idea.",
        category="OUTDOOR",
        min_time=30,
        max_time=60,
        min_budget=0,
        max_budget=0,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Recipe-from-the-fridge",
        "Cook using what you already have.",
        category="HOME",
        min_time=25,
        max_time=60,
        min_budget=0,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Dessert and wander",
        "Pair something sweet with a short stroll.",
        category="FOOD",
        min_time=25,
        max_time=50,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Campus talk drop-in",
        "Sit in on something open and informal.",
        category="CULTURE",
        min_time=45,
        max_time=90,
        min_budget=0,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Reading cafe session",
        "Order something simple and read without rushing.",
        category="FOOD",
        min_time=45,
        max_time=90,
        min_budget=5,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Mini solo date",
        "Treat one small outing like a tiny celebration.",
        category="FOOD",
        min_time=45,
        max_time=90,
        min_budget=10,
        max_budget=20,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Creative corner time",
        "Spend an hour designing, writing, or sketching.",
        category="CLASS",
        min_time=60,
        max_time=120,
        min_budget=0,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Slow brunch wander",
        "Combine a relaxed meal with light exploring.",
        category="FOOD",
        min_time=60,
        max_time=120,
        min_budget=10,
        max_budget=25,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Workout burst",
        "Run through a fast bodyweight circuit.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Partner workout sprint",
        "Move through a quick circuit together.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Pickup game drop-in",
        "Join a casual game already happening nearby.",
        category="FITNESS",
        min_time=45,
        max_time=90,
        min_budget=0,
        max_budget=15,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Speed clean sprint",
        "Set a timer and reset one small space.",
        category="HOME",
        min_time=15,
        max_time=25,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Power walk reset",
        "Pick up your pace and clear your head.",
        category="OUTDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Stairs challenge loop",
        "Repeat a short staircase route for a few rounds.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Game night moment",
        "Invite a friend over for a few quick rounds.",
        category="SOCIAL",
        min_time=60,
        max_time=120,
        min_budget=0,
        max_budget=20,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Scenic cycling loop",
        "Ride a steady route and come back sharper.",
        category="OUTDOOR",
        min_time=30,
        max_time=75,
        min_budget=0,
        max_budget=10,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Pop-up workshop",
        "Try a hands-on session and make something small.",
        category="CLASS",
        min_time=60,
        max_time=120,
        min_budget=15,
        max_budget=30,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Themed dinner plan",
        "Make the meal itself the main event.",
        category="FOOD",
        min_time=75,
        max_time=150,
        min_budget=15,
        max_budget=30,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Step count challenge",
        "Pick a short route and keep it playful.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Quick dance break",
        "Play one song and move without overthinking.",
        category="FITNESS",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Park circuit burst",
        "Use a bench and open space for a fast reset.",
        category="FITNESS",
        min_time=20,
        max_time=40,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Long photo wander",
        "Pick a route and collect a themed set.",
        category="OUTDOOR",
        min_time=60,
        max_time=120,
        min_budget=0,
        max_budget=10,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Market energy lap",
        "Walk through quickly and explore with intent.",
        category="OUTDOOR",
        min_time=30,
        max_time=60,
        min_budget=5,
        max_budget=15,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Board game drop-in",
        "Keep it light but lively.",
        category="SOCIAL",
        min_time=60,
        max_time=120,
        min_budget=5,
        max_budget=20,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Snack crawl moment",
        "Try one quick bite and move on.",
        category="FOOD",
        min_time=30,
        max_time=60,
        min_budget=10,
        max_budget=25,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Sunrise start",
        "Step outside before the day fully begins.",
        category="OUTDOOR",
        min_time=15,
        max_time=30,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
        is_outdoor=True,
    ),
    build_activity(
        "Cold splash reset",
        "End your shower with a brief cool finish.",
        category="HOME",
        min_time=10,
        max_time=15,
        min_budget=0,
        max_budget=0,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Train loop escape",
        "Ride somewhere just for the change of scene.",
        category="OUTDOOR",
        min_time=60,
        max_time=120,
        min_budget=10,
        max_budget=25,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
        is_outdoor=True,
    ),
    build_activity(
        "Tea shop pause",
        "Pick one warm drink and let yourself slow down for a minute.",
        category="FOOD",
        min_time=15,
        max_time=25,
        min_budget=4,
        max_budget=10,
        moods=["low"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Pastry pick-up stroll",
        "Grab one small treat and pair it with a short wander.",
        category="FOOD",
        min_time=15,
        max_time=30,
        min_budget=5,
        max_budget=12,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Mini flower stop",
        "Pick up one stem or a tiny bunch and bring it back with you.",
        category="CULTURE",
        min_time=15,
        max_time=25,
        min_budget=6,
        max_budget=15,
        moods=["low"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Smoothie reset",
        "Order something cold and fresh, then take a short pause before moving on.",
        category="FOOD",
        min_time=15,
        max_time=25,
        min_budget=5,
        max_budget=10,
        moods=["medium"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Snack stop chat",
        "Meet up for one quick bite and keep the catch-up light.",
        category="FOOD",
        min_time=15,
        max_time=30,
        min_budget=6,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.FRIENDS,
    ),
    build_activity(
        "Pocket gallery visit",
        "Step into one small exhibit or shop corner and stay just long enough to notice something.",
        category="CULTURE",
        min_time=20,
        max_time=30,
        min_budget=8,
        max_budget=15,
        moods=["medium"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Protein shake run",
        "Pick a quick stop, order something simple, and keep your momentum going.",
        category="FOOD",
        min_time=15,
        max_time=25,
        min_budget=6,
        max_budget=12,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Express studio pass",
        "Drop into one short guided session and leave with your energy up.",
        category="CLASS",
        min_time=20,
        max_time=30,
        min_budget=12,
        max_budget=18,
        moods=["high"],
        social_type=Activity.SocialType.SOLO,
    ),
    build_activity(
        "Quick climbing slot",
        "Use a short booked slot for one focused burst of movement.",
        category="FITNESS",
        min_time=20,
        max_time=30,
        min_budget=10,
        max_budget=20,
        moods=["high"],
        social_type=Activity.SocialType.EITHER,
    ),
    build_activity(
        "Juice bar meet-up",
        "Meet a friend for something quick, bright, and a little energising.",
        category="FOOD",
        min_time=15,
        max_time=25,
        min_budget=6,
        max_budget=14,
        moods=["high"],
        social_type=Activity.SocialType.FRIENDS,
    ),
]


for index, payload in enumerate(SEED_ACTIVITIES):
    aliases = [payload["title"]]
    if index < len(LEGACY_TITLES):
        aliases.append(LEGACY_TITLES[index])
    payload["_lookup_titles"] = aliases


class Command(BaseCommand):
    help = "Seed starter activities for the daily random events app."

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for payload in SEED_ACTIVITIES:
            lookup_titles = payload["_lookup_titles"]
            defaults = {
                key: value for key, value in payload.items() if not key.startswith("_")
            }

            existing = (
                Activity.objects.filter(title__in=lookup_titles).order_by("id").first()
            )

            if existing:
                for field, value in defaults.items():
                    setattr(existing, field, value)
                existing.save()
                updated_count += 1
                continue

            Activity.objects.create(**defaults)
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete: {created_count} created, {updated_count} updated."
            )
        )
