# Generated by Django 6.0.3 on 2026-03-03 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('min_time_minutes', models.PositiveIntegerField()),
                ('max_time_minutes', models.PositiveIntegerField()),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_budget', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('social_type', models.CharField(choices=[('SOLO', 'Solo'), ('FRIENDS', 'Friends'), ('EITHER', 'Either')], db_index=True, default='EITHER', max_length=20)),
                ('is_outdoor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='daily_rando_categor_f95250_idx'), models.Index(fields=['social_type', 'is_active'], name='daily_rando_social__44046d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_time_minutes__gte', models.F('min_time_minutes'))), name='activity_time_range_valid'), models.CheckConstraint(condition=models.Q(('max_budget__gte', models.F('min_budget'))), name='activity_budget_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mood', models.CharField(choices=[('RELAXED', 'Relaxed'), ('ENERGETIC', 'Energetic'), ('CREATIVE', 'Creative'), ('SOCIAL', 'Social'), ('LOW_EFFORT', 'Low Effort')], max_length=20)),
                ('social_preference', models.CharField(choices=[('SOLO', 'Solo'), ('FRIENDS', 'Friends'), ('EITHER', 'Either')], default='EITHER', max_length=20)),
                ('excluded_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_no', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='daily_random_events.activity')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='daily_random_events.generationrequest')),
            ],
            options={
                'ordering': ['rank_no'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='daily_random_events.suggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'created_at'], name='daily_rando_user_id_f5198e_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['request', 'rank_no'], name='daily_rando_request_122c51_idx'),
        ),
        migrations.AddConstraint(
            model_name='suggestion',
            constraint=models.UniqueConstraint(fields=('request', 'rank_no'), name='suggestion_request_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='suggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('request',), name='single_accepted_suggestion_per_request'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='daily_rando_user_id_34d2ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitylog',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('status', 'COMPLETED'), _connector='OR'), name='rating_requires_completed_status'),
        ),
    ]
