# Generated by Django 6.0.3 on 2026-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_random_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("COMPLETED", "Completed"),
                    ("SKIPPED", "Skipped"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACCEPTED")),
                fields=("user",),
                name="single_pending_activity_log_per_user",
            ),
        ),
    ]
