# Generated by Django 6.0.3 on 2026-03-03 21:10

from django.db import migrations, models


LEGACY_MOOD_LEVELS = {
    "RELAXED": "low",
    "LOW_EFFORT": "low",
    "CREATIVE": "medium",
    "SOCIAL": "medium",
    "ENERGETIC": "high",
}


def normalize_mood_levels(apps, schema_editor):
    Activity = apps.get_model("daily_random_events", "Activity")
    GenerationRequest = apps.get_model("daily_random_events", "GenerationRequest")

    for request in GenerationRequest.objects.all().iterator():
        normalized = LEGACY_MOOD_LEVELS.get(request.mood, request.mood)
        if normalized != request.mood:
            request.mood = normalized
            request.save(update_fields=["mood"])

    for activity in Activity.objects.all().iterator():
        raw_tags = list(activity.mood_tags or [])
        normalized_tags = []
        seen = set()

        for tag in raw_tags:
            normalized = LEGACY_MOOD_LEVELS.get(str(tag).upper(), str(tag).lower())
            if normalized not in seen:
                normalized_tags.append(normalized)
                seen.add(normalized)

        if normalized_tags != raw_tags:
            activity.mood_tags = normalized_tags
            activity.save(update_fields=["mood_tags"])


class Migration(migrations.Migration):

    dependencies = [
        ("daily_random_events", "0002_activitylog_accepted_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationrequest",
            name="mood",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            normalize_mood_levels,
            migrations.RunPython.noop,
        ),
    ]
