# Generated by Django 6.0.3 on 2026-03-05 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_random_events', '0003_normalize_mood_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_entries', to='daily_random_events.suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='daily_rando_user_id_d2118c_idx'), models.Index(fields=['user', 'suggestion'], name='daily_rando_user_id_b027a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'suggestion'), name='saved_suggestion_user_unique')],
            },
        ),
    ]
